version: '2'
#http://stackoverflow.com/questions/32360615/docker-compose-nodejs-mongodb
services:
  hotel-node:
    build:
      context: .
      dockerfile: node.dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "3000:3000"
    networks:
      - hotel-net
  hotel-db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - hotel-net

networks:
    hotel-net:
      driver: bridge